config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users

  

  resources :submissions do
  	member do
      put "like", to: "submissions#upvote"
      put "dislike", to: "submissions#downvote"
	  end

    resources :comments
  end


  root 'submissions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :submission
end

app/models/submission.rb
class Submission < ApplicationRecord
	belongs_to :user
	has_many :comments

	acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :submissions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    
  end
  # POST /comments
  # POST /comments.json
  def create
    @submission = Submission.find(params[:submission_id])
    @comment = @submission.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @submission, notice: 'Comment was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end



  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:submission_id, :body, :user_id)
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.order(cached_votes_total: :desc)
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @submission = current_user.submissions.build
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  # POST /submissions.json
  def create
    

    @submission = current_user.submissions.build(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  def upvote
    @submission = Submission.find(params[:id])

    #assign upvote to current user
    @submission.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @submission = Submission.find(params[:id])

    #assign upvote to current user
    @submission.downvote_by current_user
    redirect_to :back
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
  <div class="comments-wrapper clearfix">
    <div class="null-left">
      <p><small> <%= comment.user.email %> <strong><%= time_ago_in_words(comment.created_at) %></strong> ago </small></p>
      <p class="lead"><%= comment.body %></p>
    </div>
  </div>

  <% if comment.user == current_user %>
    <%= link_to 'delete', comment, method: :delete, data: { confirm: 'are you sure?'} %>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :submission_id %>
    <%= f.number_field :submission_id %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Submission</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.submission_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Submission:</strong>
  <%= @comment.submission_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackernews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">

  </head>

  <body>
    <div id="main" class="container">
      <header class="navbar navbar-default" role="navigation">

        <div id="logo" class="navbar-brand"><%= link_to "Hacker News", root_path %></div>
        <nav class="collapse navbar-collapse navbar-ex-1-collapse">
          <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "submit", new_submission_path %></li>
            <li><%= link_to "account", edit_user_registration_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "logout", destroy_user_session_path, :method => :delete %></li>
          </ul>

          <% else %>
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "login", new_user_session_path %></li>
          </ul>
          <% end %>
        </nav>

      </header>

      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>

      <div id="container" class="center-block">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/submissions/_form.html.erb
<%= form_for(submission) do |f| %>
  <% if submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<table>
  <tbody>
    <% @submissions.each do |submission| %>
      <tr class="post">
        <td>
          <%= link_to like_submission_path(submission), method: :put do %>
            <i class="fa fa-caret-up fa-lg " aria-hidden="true"></i>
          <% end %>

          <%= link_to submission.title, submission.url, class: "title" %>
          <%= link_to submission.url, "(#{submission.url})", target: "_blank" %>
        </td>
        <tr class="post">
          <td> <p><%= submission.get_upvotes.size %> points by <%= submission.user.email %> <%= time_ago_in_words(submission.created_at) %> ago | <%= link_to "#{submission.comments.count} comments", submission %> </p></td>
        </tr>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<div class="page-header">
  <h4>
    <%= link_to like_submission_path(@submission), method: :put do %>
      <i class="fa fa-caret-up fa-lg " aria-hidden="true"></i>
    <% end %>
    <%= @submission.title %>
    <a href="<%= @submission.url %>"><%= @submission.url %></a>
  </h4>
  <p><%= @submission.get_upvotes.size %> points by <%= @submission.user.email %> <%= time_ago_in_words(@submission.created_at) %> ago | <%= link_to "#{@submission.comments.count} comments", @submission %> </p>
  <br>

  <%= simple_form_for [@submission, Comment.new] do |f| %>
    <%= f.text_area :body, class: "form-control" %>
    <br>
    <%= f.submit "add comment" %>
  <% end %>

  <div id="comments">
    <%= render :partial => @submission.comments %>
  </div>
</div>